name: Generate random failure
on: push
jobs:
  randomly-failing-job:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - name: Generate 0 or 1
        id: generate_number
        run: |
          echo "random_number=$(($RANDOM % 2))" >> $GITHUB_OUTPUT
          printf '%s\n' "$random_number"

      - name: Pass or fail
        run: |
          if [[ "${{ steps.generate_number.outputs.random_number }}" == "0" ]]; then 
            echo "Random number generated: 0"
          else
            echo "Random number generated: 1"
          fi
